// <auto-generated />
using System;
using BaseClasses.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseClasses.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241122102926_First5Classes")]
    partial class First5Classes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseClasses.Models.City", b =>
                {
                    b.Property<int>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCity"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCity");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BaseClasses.Models.Group", b =>
                {
                    b.Property<int>("IdGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGroup"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdModeratorIdUser")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGroup");

                    b.HasIndex("IdModeratorIdUser");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BaseClasses.Models.GroupRequest", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdGroup")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser", "IdGroup");

                    b.HasIndex("IdGroup");

                    b.ToTable("GroupRequests");
                });

            modelBuilder.Entity("BaseClasses.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<bool>("Administrator")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdHomeIdCity")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Privacy")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdHomeIdCity");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BaseClasses.Models.UserGroup", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdGroup")
                        .HasColumnType("int");

                    b.HasKey("IdUser", "IdGroup");

                    b.HasIndex("IdGroup");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("BaseClasses.Models.Group", b =>
                {
                    b.HasOne("BaseClasses.Models.User", "IdModerator")
                        .WithMany()
                        .HasForeignKey("IdModeratorIdUser");

                    b.Navigation("IdModerator");
                });

            modelBuilder.Entity("BaseClasses.Models.GroupRequest", b =>
                {
                    b.HasOne("BaseClasses.Models.Group", "Group")
                        .WithMany("GroupRequests")
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseClasses.Models.User", "User")
                        .WithMany("GroupRequests")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseClasses.Models.User", b =>
                {
                    b.HasOne("BaseClasses.Models.City", "IdHome")
                        .WithMany("Users")
                        .HasForeignKey("IdHomeIdCity");

                    b.Navigation("IdHome");
                });

            modelBuilder.Entity("BaseClasses.Models.UserGroup", b =>
                {
                    b.HasOne("BaseClasses.Models.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseClasses.Models.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseClasses.Models.City", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BaseClasses.Models.Group", b =>
                {
                    b.Navigation("GroupRequests");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("BaseClasses.Models.User", b =>
                {
                    b.Navigation("GroupRequests");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
